# Site settings
title: Julia Grill
tag_text: Julia Grill
description: The personal site for Julia Grill, a high school student/iOS developer based in Vienna, Austria.

# Build settings
markdown: kramdown

exclude: ["README.md"]
